//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStokProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSATISLAR
    {
        public int satisid { get; set; }
        public Nullable<int> urunid { get; set; }
        public Nullable<int> musteriid { get; set; }
        public Nullable<byte> adet { get; set; }
        public Nullable<decimal> satisFiyati { get; set; }
    
        public virtual TBLMUSTERILER TBLMUSTERILER { get; set; }
        public virtual TBLURUNLER TBLURUNLER { get; set; }
    }
}
