//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStokProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUNLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLURUNLER()
        {
            this.TBLSATISLAR = new HashSet<TBLSATISLAR>();
        }
    
        public int urunid { get; set; }
        public string urunAd { get; set; }
        public string urunMarka { get; set; }
        public Nullable<short> urunKategori { get; set; }
        public Nullable<decimal> urunFiyat { get; set; }
        public Nullable<byte> Stok { get; set; }
    
        public virtual TBLKATEGRORILER TBLKATEGRORILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSATISLAR> TBLSATISLAR { get; set; }
    }
}
